// Copyright (c) Canaan Inc. All rights reserved.
// Licensed under the Apache license. See LICENSE file in the project root for full license information.

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Text.Json;
using System.Text.Json.Serialization;
using Google.OrTools.Sat;
using Nncase.CostModel;
using Nncase.IR;
using Nncase.IR.Math;
using Nncase.Passes;
using Nncase.PatternMatch;
using Nncase.Tests.TestFixture;
using Xunit;
using static Nncase.IR.F.Math;
using static Nncase.PatternMatch.F.Math;
using static Nncase.PatternMatch.F.Tensors;
using static Nncase.PatternMatch.Utility;

namespace Nncase.Tests.EGraphTest;

[AutoSetupTestMethod(InitSession = true)]

public class UnitTestExtractor : TestClassBase
{
    public UnitTestExtractor()
    {
        CompileOptions.DumpFlags = Diagnostics.DumpFlags.EGraphCost | Diagnostics.DumpFlags.Rewrite | Diagnostics.DumpFlags.Compile | Diagnostics.DumpFlags.ImportOps | Diagnostics.DumpFlags.PassIR;
    }

    [Fact]
    public void Test_for_Extractor_dump()
    {
        var egraph = new EGraph();
        var a = new Var(TensorType.Scalar(DataTypes.Float64)); // var a_1 = new Var(TensorType.Scalar(DataTypes.UInt32));
        Expr b = a * 2.0; // Expr c = a_1 << 1;

        var aid = egraph.Add(a);
        var bId = egraph.Add(b); // var cId = egraph.Add(c);

        // did or eid 会变成最后的一个root
        var root = egraph.Add(b / 2.0); // var eId = egraph.Add(c / 2);
        EGraphPrinter.DumpEgraphAsDot(egraph, "exampleMerge8.dot");

        // 第二步（2）：基于rule直接对图进行重写，这里是a * b / c = a * (b / c) , x / x = 1
        _ = CompilerServices.ERewrite(egraph, new IRewriteRule[] { new Passes.Rules.Arithmetic.ReassociateDiv(), new Passes.Rules.Arithmetic.XDivX() }, new());

        // todo : define pattern and rewrite  ||   x * 1 = x  || use pattern to settle
        var pattern = PatternMatch.F.Math.Mul(IsWildcard("lhs"), IsConst(1.0d));

        if (CompilerServices.TryMatchRoot(root.Nodes, pattern, out var eResults))
        {
            egraph.Union(aid, root);
            egraph.Rebuild();
        }

        // egraph_changed.Rebuild(); not the problem && egraph will be modified not only egraph_changed
        EGraphPrinter.DumpEgraphAsDot(egraph, "exampleMerge9_0.dot");

        // created by evaluator
        var evaluator = new EGraphCostEvaluator(root.Find(), CompileOptions, null);
        var costmodel = evaluator.Evaluate();

        // cost/pick.dot是由extrator生成的
        var extractor = new EGraphExtractor(costmodel);
        EGraphExtractConstrains[]? constrains = null;
        var selected = extractor.Extract(root.Find(), egraph, constrains ?? Array.Empty<EGraphExtractConstrains>());
        CompilerServices.DumpIR(selected, string.Empty, Dumpper.Directory);

        // 或者更加集成的方法
        // var res = EGraphExtensions.Extract(egraph, root.Find(), CompileOptions, null, constrains);
    }

    [Fact]
    public void Test_dump_json_for_smoothe()
    {
        var egraph = new EGraph();
        var a = new Var(TensorType.Scalar(DataTypes.Float64)); // var a_1 = new Var(TensorType.Scalar(DataTypes.UInt32));
        Expr b = a * 2.0; // Expr c = a_1 << 1; 左移是针对int的操作，但是除以是float的操作，融合不到一块

        var aid = egraph.Add(a);
        var bId = egraph.Add(b); // var cId = egraph.Add(c);

        // did or eid 会变成最后的一个root
        var root = egraph.Add(b / 2.0); // var eId = egraph.Add(c / 2);

        // 第二步（2）：基于rule直接对图进行重写，这里是a * b / c = a * (b / c) , x / x = 1
        _ = CompilerServices.ERewrite(egraph, new IRewriteRule[] { new Passes.Rules.Arithmetic.ReassociateDiv(), new Passes.Rules.Arithmetic.XDivX() }, new());

        // todo : define pattern and rewrite  ||   x * 1 = x  || use pattern to settle
        var pattern = PatternMatch.F.Math.Mul(IsWildcard("lhs"), IsConst(1.0d));

        if (CompilerServices.TryMatchRoot(root.Nodes, pattern, out var eResults))
        {
            egraph.Union(aid, root);
            egraph.Rebuild();
        }

        EGraphPrinter.DumpEgraphAsDot(egraph, "exampleMerge9_2.dot");

        // 以上都是剽窃自上一个测试的图
        // var allClasses = egraph.Classes.ToList();
        var rootClass = root.Find();
        var extractor = new SmoothEExtractor(CompileOptions);
        var extracted = extractor.Extract(rootClass, egraph, Array.Empty<EGraphExtractConstrains>());

        Assert.NotNull(extracted);
        Assert.True(
            File.Exists(Path.Combine("egraph_flex_dump.json")),
            "egraph_flex_dump.json should be generated by SmoothEExtractor.");
    }
}
